### ISSUE TITLE
Crashes Server

### ISSUE THREAD

**Issue by deadspidervenom** [arcanoren/arcanaPlusPlus#1]
When i tried to load my server it would not load with a error about loot and loot table having no such method.
[2021-05-05-7.log](https://github.com/arcanoren/arcanaPlusPlus/files/6431360/2021-05-05-7.log)

**Comment by arcanoren** [comment]
> When i tried to load my server it would not load with a error about loot and loot table having no such method.
> [2021-05-05-7.log](https://github.com/arcanoren/arcanaPlusPlus/files/6431360/2021-05-05-7.log)
 Sorry by the delay. I can only imagine that is caused by some mod conflict, but I couldn't know what. I know that error is related to a modification that I've made in leaves loot table, but, this I used a safe method to this. If you could identify any mod that change the drop of tree leaves, it is a likely that mod is the cause by conflict.
